In [35]:
import numpy as np

l=[2, 8, 7, 11]
Q1=np.array(l)
#print(Q1)

Q2=np.array([[1,2,3],[4,5,6],[7,8,9]])
#print(Q2)

Q3=Q2[:, [1]]
#print(Q3)

np.random.seed(6)
Q4=np.random.randint(10, size=(5,6))
#print(Q4)

Q5=Q4[0:3, 1:3]
#print(Q5)

Q6=Q4[3:, 2:5]
#print(Q6)

Q7=Q4[2:4, 1:3]
#print(Q7)

Q8=Q4[:, 2:4]
#print(Q8)

Q9=Q4[3:5]
#print(Q9)

[ 2  8  7 11]
[[9 3 4 0 9 1]
 [9 1 4 1 8 2]
 [4 2 5 9 6 2]
 [5 5 1 4 5 0]
 [2 2 3 5 9 5]]
[[3 4]
 [1 4]
 [2 5]]
[[1 4 5]
 [3 5 9]]
[[2 5]
 [5 1]]
[[4 0]
 [4 1]
 [5 9]
 [1 4]
 [3 5]]
[[5 5 1 4 5 0]
 [2 2 3 5 9 5]]
