In [35]:
import numpy as np

np.random.seed(100)
a= np.random.rand(20)
# print(a)
Q1 = a.sum()
Q2 = a.max()

# print(Q1)
# print(Q2)
# print('---------------')


Q1 = np.sum(a)
Q2 = np.max(a)

# print(Q1)
# print(Q2)
# print('---------------')


a= np.random.rand(4,5)
Q3= np.sum(a, axis=1)
# print('------------ a:')
# print(a)
# print('------------ sum a:')
# print(Q3)

a=[2,3,np.nan,5]
# print('------------ a:')
# print(a)
Q5=np.nansum(a)
# print('------------ Q5:')
# print(Q5)
# print('---------------')



a=np.random.rand(4)
b=np.random.rand(4)
# print('a:')
# print(a)

# print('b:')
# print(b)

Q6=np.concatenate((a, b))
# print('Q6:')
# print(Q6)


q7= np.random.rand(4,4)
Q7=np.concatenate((q7, q7))
print(Q7)

np.split(Q7, 2, axis=0)



[[0.28589569 0.85239509 0.97500649 0.88485329]
 [0.35950784 0.59885895 0.35479561 0.34019022]
 [0.17808099 0.23769421 0.04486228 0.50543143]
 [0.37625245 0.5928054  0.62994188 0.14260031]
 [0.28589569 0.85239509 0.97500649 0.88485329]
 [0.35950784 0.59885895 0.35479561 0.34019022]
 [0.17808099 0.23769421 0.04486228 0.50543143]
 [0.37625245 0.5928054  0.62994188 0.14260031]]


[array([[0.28589569, 0.85239509, 0.97500649, 0.88485329],
        [0.35950784, 0.59885895, 0.35479561, 0.34019022],
        [0.17808099, 0.23769421, 0.04486228, 0.50543143],
        [0.37625245, 0.5928054 , 0.62994188, 0.14260031]]),
 array([[0.28589569, 0.85239509, 0.97500649, 0.88485329],
        [0.35950784, 0.59885895, 0.35479561, 0.34019022],
        [0.17808099, 0.23769421, 0.04486228, 0.50543143],
        [0.37625245, 0.5928054 , 0.62994188, 0.14260031]])]