In [49]:
import numpy as np

Q1 = np.zeros(20, dtype=float)
Q2 = np.ones([4,5], dtype=int)
Q3 = np.array([2]*10, dtype=float).reshape(2,5)
Q4 = np.arange(50, dtype=float)
Q5 = np.linspace(4, 18, 9)
Q6 = np.zeros([5,5], dtype=int)
np.fill_diagonal(Q6, 1)

np.random.seed(10)
Q7=np.random.rand(4,2)

np.random.seed(9)
Q8=np.random.randint(0,15, size=(4,2,5))
Q9 = Q8.size



[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
