In [16]:
import numpy as np

np.random.seed(77)
Q1=np.random.randint(50, size=(8,6))
#print(Q1)

Q2 = Q1[2:7, 4:]
Q3 = Q1[2:, 3:5]
Q4 = Q3.reshape(2,6)
Q5= Q4.reshape(3,4)

Q6 = np.array([
               ('Janetta', 'Lydia', 58, 58),
               ('Deb', 'Albin', 68, 50),
               ('Minato', 'Vanja', 78, 38),
               ('Maurine', 'Peter', 77, 57),
               ('Niketas', 'Justine', 70, 60)
              ], 
              dtype=[('Name', 'U20'), ('Last','U20'), ('Height','int16'), ('Age', 'int16')])



[[23 31 20 20 43 37]
 [24 31 32 39 44 19]
 [32 36 36 47 14 15]
 [10  7 35  1 11 17]
 [ 6 20 37 33 40  1]
 [42  4 29 41 28  0]
 [28 40 25 37 11  3]
 [18 36 21 22 45 14]]


array([('Janetta', 'Lydia', 58, 58), ('Deb', 'Albin', 68, 50),
       ('Minato', 'Vanja', 78, 38), ('Maurine', 'Peter', 77, 57),
       ('Niketas', 'Justine', 70, 60)],
      dtype=[('Name', '<U20'), ('Last', '<U20'), ('Height', '<i2'), ('Age', '<i2')])